---
env:
  node: true
  commonjs: true
  es6: true
extends: airbnb
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - react-native
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  react/jsx-filename-extension: 0
  react-native/no-unused-styles: 2
  react-native/split-platform-components: 2
  react-native/no-inline-styles: 2
  react-native/no-color-literals: 2
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .android.js
        - .ios.js
